statements = [
{
"title":"Social Security",
"text":"Jim’s bill to expand Social Security will increase benefits for low-income senior citizens and people with disabilities by more than $1,300 a year. It is fully paid for by making those with incomes and capital gains over $250,000 a year – pay the same rate into Social Security as working families. This bill will also extend the solvency of Social Security into the year 2070 – ensuring that Social Security can pay every benefit owed to every eligible American for the next 50 years."
},
{
"title":"Covid-19 Response",
"text":"<p>The American people deserve an urgent, robust, and professional response to the growing public health and economic crisis caused by the coronavirus (COVID-19) outbreak. That is why Jim Gilmore is outlining a plan to mount</p><ul><li>A decisive public health response that ensures the wide availability of free testing; the elimination of all cost barriers to preventive care and treatment for COVID-19; the development of a vaccine; and the full deployment and operation of necessary supplies, personnel, and facilities.</li><li>A decisive economic response that starts with emergency paid leave for all those affected by the outbreak and gives all necessary help to workers, families, and small businesses that are hit hard by this crisis. Make no mistake: this will require an immediate set of ambitious and progressive economic measures, and further decisive action to address the larger macro-economic shock from this outbreak.</li></ul>"
},
{
"title":"National Debt",
"text":"To pay for this, we will impose a tax of a fraction of a percent on the Wall Street speculators and international investors who nearly destroyed the economy a decade ago. This Wall Street speculation tax will raise $5 trillion over the next ten years. It works by placing a 0.1 percent tax on stock trades – 10 cents on every $100 of stock – a 0.1 percent fee on bond trades, and a 0.05 percent fee on derivative trades.  If Wall Street and foreign investors can be bailed out for several trillion dollars, 320 million Americans can and will be bailed out of the National Deficit burden which sees tax payers money being spent to pay off the interest on loans from foreign banks. Some 40 countries throughout the world have imposed a similar tax, including Britain, South Korea, Hong Kong, Brazil, Germany, France, Switzerland and China."
},
{
"title":"College Loans",
"text":"Unbelievably, 45 percent of college students report struggling with hunger, 56 percent report struggling with the cost of housing, and 17 percent say they experienced homelessness. In the richest country in the history of the world, students should not have to starve in order to get an education.  The average college student in the U.S. graduates with close to $30,000 in student loans and one in six college students will be stuck with over $50,000 in student loan debt after graduation. The reality we face is that more than half of students who enroll in college don’t complete a degree. Millions are leaving school with no degree and thousands of dollars in debt. We will place a cap on student loan interest rates going forward. The federal government shouldn’t make billions of dollars in profit off student loans while students are drowning in debt. We should invest in young Americans – not leverage their futures. Today, the average interest rate on undergraduate student loans is more than 5 percent. Under this proposal, we will cap student loan interest rates at 1.88 percent.  For those taking the highest paid, most economically valuable majors such as computer science, physics, chemistry, engineering, math, medicine, and nursing, we will provide all qualified candidates with a free state school education plus housing and a stipend for food."
},
{
"title":"Medicare for All",
"text":"We are the only 1st world country that doesn’t provide a free basic national health service to our citizens, so people can look after their health without going into debt.  We can’t maintain the status quo that leaves tens of millions of people either uninsured or with substandard coverage that leaves them on the hook for crushing medical bills. Gilmore’s Medicare for All plan will cover everyone, ensure long-term care for our seniors, and put $11 trillion back in the pockets of American families by eliminating premiums, copays, and deductibles. And we make up the difference with targeted spending cuts, negotiating drug prices, and by cracking down on tax evasion and fraud. Not one penny more  in middle-class tax increases.  We can end the stranglehold of healthcare costs on American families and free Americans who are afraid to leave their jobs for new opportunities because they are terrified of losing their insurance.  In this supposedly capitalist country, Americans can’t even price shop the cost of drugs, ambulance rides, hospital stays, salt water solutions, and other medical services because pharmaceutical companies, health insurance, and medical practices have lobbied the government to keep these hidden.  $12,378. That’s how much an average family of four with employer-sponsored insurance personally spent per year on employee premium contributions and out-of-pocket costs in 2018. And this figure has increased each year.  87 million. That’s how many American adults in 2018 were uninsured or “underinsured” – meaning either they have no insurance or their so-called health insurance is like a car with the engine missing. It looks fine sitting on the lot, but is inadequate if they actually need to use it. Nearly one in every two adults not currently on Medicare has no insurance or unreliable insurance.  37 million American adults didn’t fill a prescription last year because of costs. 36 million people skipped a recommended test, treatment, or follow-up because of costs. 40 million people didn’t go to a doctor to check out a health problem because of costs. 57 million people had trouble covering their medical bills.  People should have to choose between medicine and food, no one should go bankrupt trying to stay healthy with conventional medicine.  With COVID-19 people aren’t just hurting themselves by not getting medical attention, they are hurting family and friends and this puts the whole of America in danger.  It isn’t just a personal health risk, it is a public health crisis to not have a national healthcare system competing against private health insurance."
},
{
"title":"Homelessness",
"text":"Gilmore’s housing plan will lower rents by 10%, help close the racial wealth gap, and create 1.5 million new jobs.  My plan will bring down rental costs by 10% by addressing the root causes of the problem: a severe lack of affordable housing supply, and state and local land-use rules that needlessly drive up housing costs. The rising cost of rent reflects a basic supply-and-demand problem. There aren’t enough places to rent that are affordable to lower-income families. That’s because developers can usually turn bigger profits by building fancier new units targeted at higher-income families rather than units targeted at lower-income families. The result is a huge hole in the marketplace.  That hole ends up raising costs for everyone. Without enough affordable options, lower-income families have to stretch their budgets to try to find housing. They end up taking units that would otherwise go to middle-class families. Middle-class families, in turn, have to stretch their budgets to secure housing that might otherwise go to even richer families."
},
{
"title":"Prison Reform",
"text":"The United States makes up 5% of the world’s population, but nearly 20% of the world’s prison population. We have the highest rate of incarceration in the world, with over 2 million people in prison and jail.  Tough on crime shouldn’t mean keeping people locked up forever for a third offense of being caught with drugs.  Currently prisons are referred to by inmates as a crime college for cons.  They foster violence, encourage racial segregation, treat inmates as animals instead of training them to be better members of society.  We shouldn’t have mandatory minimums except for physical assaults, murders, rape, and sex crimes against children.  This prison pipeline needs reform at every step and that includes how police officers are trained to deal with suspects.  Police need to be given politeness training and be made to pay for crimes they commit, lying, falsifying evidence, corruption, and murder by being sent to a specially designated officer prison.  Schools need to be allowed to have more flexibility in how they enforce discipline so students get corrected early for bad behavior, long before prison becomes an option.  All prisoners should be given daily education provided by online classes and video instruction so inmates can gain the career and people skills needed to reenter society.   No-one should lose their vote because they’ve been to prison.  People do not stop being people just because they’ve broken one of society’s rules.  We could provide mental health services, treatment for addiction, housing and food, less expensively out of prison than in prison and yet some are essentially incarcerated for the crime of being poor or addicted to drugs or needing help with mental health.  It’s not equal justice when a kid with an ounce of pot can get thrown in jail, while a bank executive who launders money for a drug cartel can get a bonus. It’s long past time for us to reform our system."

}
]
